# Generated by Django 4.1.4 on 2023-01-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='likes_in_post', to='network.liking'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='posts',
        ),
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.ManyToManyField(default=None, null=True, related_name='user_posts', to='network.post'),
        ),
    ]
