# Generated by Django 4.1.4 on 2023-01-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_post_likes_remove_user_posts_user_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='posts',
            field=models.ManyToManyField(default=None, related_name='user_posts', to='network.post'),
        ),
    ]
