# Generated by Django 3.2.6 on 2021-09-02 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210831_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_followed', models.DateTimeField(auto_now=True)),
                ('following_user', models.ManyToManyField(related_name='follower', to=settings.AUTH_USER_MODEL)),
                ('user', models.ManyToManyField(related_name='followed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
