# Generated by Django 3.2.6 on 2021-09-02 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210902_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_liked', models.DateTimeField(auto_now=True)),
                ('post', models.ManyToManyField(related_name='liked_post', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
