# Generated by Django 3.2.6 on 2021-09-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20210902_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liking',
            name='post',
            field=models.ManyToManyField(related_name='liked_post', to='network.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='likes_in_post', to='network.Post'),
        ),
    ]
