# Generated by Django 3.1 on 2020-08-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200815_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='initial_bid',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
