# Generated by Django 3.1 on 2020-08-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200815_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='initial_bid',
            field=models.IntegerField(default=0),
        ),
    ]
