# Generated by Django 3.1 on 2020-08-19 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200816_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='date_of_listing',
            new_name='date_created',
        ),
    ]
