# Generated by Django 3.1 on 2020-09-02 10:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200902_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.ManyToManyField(blank=True, default=None, related_name='user_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
