# Generated by Django 3.1 on 2020-09-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20200903_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='listing',
            field=models.ManyToManyField(blank=True, related_name='listing', to='auctions.Listing'),
        ),
    ]
