# Generated by Django 3.1.1 on 2020-09-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200903_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='listing',
            field=models.ManyToManyField(blank=True, related_name='user_listing', to='auctions.Listing'),
        ),
    ]
