# Generated by Django 3.1.1 on 2020-09-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20200908_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='listing',
            field=models.ManyToManyField(blank=True, default=None, related_name='watchlist', to='auctions.Listing'),
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
